#!/bin/sh

set -ex

cargo build --release --manifest-path ../Cargo.toml
gcc -O3 -DDEBUG -o simple simple.c -ansi -Wall -I../include -L../../target/release -lisosurface
# If you're using libisosurface.a, then you'll need to link other stuff:
# -lutil -ldl -lpthread -lgcc_s -lc -lm -lrt -lutil -lrure
