#!/bin/sh

set -ex

cargo rustc --release --manifest-path ../Cargo.toml -- --print native-static-libs
gcc -O3 -DDEBUG -o simple simple.c -ansi -Wall -I../include -L../../target/release -lisosurface
# If you're using libisosurface.a as a static library, use:
# Linux (gcc)
# gcc -O3 -DDEBUG -o simple simple.c -ansi -Wall -I../include ../../target/release/libisosurface.a -lutil -lutil -ldl -lrt -lpthread -lgcc_s -lc -lm -lrt -lpthread -lutil -lutil 
# macOS (clang)
# gcc -O3 -DDEBUG -o simple simple.c -ansi -Wall -I../include ../../target/release/libisosurface.a -lSystem -lresolv -lc -lm
