def recur(idx):
    n = len(idx)
    if len(idx) < 4:
        print 'if u' + str(n) + ' >= 0. {'
        if len(idx) < 3:
            print '    let u' + str(n) + ' = u' + str(n) + ' + tiny;'
        idx.append(0)
        recur(idx)
        idx.pop()
        print('} else {')
        idx.append(1)
        recur(idx)
        idx.pop()
        print('}')
        return

    n = sum(idx)

    if n == 0 or n == 4:
        return

    zero = []
    one = []
    for i in range(0, 4):
        if idx[i]:
            one.append(i)
        else:
            zero.append(i)

    for i in one:
        for j in zero:
            print('emit_vertex(v{i}.interpolate(&v{j}, u{i}, u{j}));'.format(i = i, j = j))

    if n == 2:
        print('emit_face([0, 1, 2]);')
        print('emit_face([2, 1, 3]);')
    elif n == 1 or n == 3:
        print('emit_face([0, 1, 2]);')

print('// START GENERATED: generated by `scripts/tetrahedron_cuts.py`')
recur([])
print('// END GENERATED')
